### ISSUE TITLE
'Create' action not detected and 'Update' action doesn't detect some columns

### ISSUE THREAD

**Issue by clararichela** [InformedPowerPlatform/MSFTPP.Plugins.CustomAudit#1]
Hi, I've tried using this plugin to track changes in dataverse tables. However, it doesn't update the Custom Audit view for newly created rows. It works for Updated rows but only for columns where there's already a data before, it doesn't detect if initially that column doesn't have any data (blank).

I've enabled auditing for all the necessary columns, and in the app I've indicated the columns that I want to track. I'm not sure why it's only working partially for Update and not working at all for Create.

Appreciate if you can advise me on this. Also, thank you for the plugin, it's really helpful

**Comment by InformedPowerPlatform** [comment]
Hi there! Can you go into the model driven app called 'Custom Audit Builder', select 'Edit Existing', and then in the Steps dropdown, do you see a Step for both Update AND Create? Auditing of the Create message is configured separately from the Update message in the plugin.

![2023-11-20_08-04-11](https://github.com/InformedPowerPlatform/MSFTPP.Plugins.CustomAudit/assets/29958333/913cb8f3-6c89-4c71-a35e-80abcd635b1b)

**Comment by clararichela** [comment]
Hi, I've included the Create Step, tried adding a new record in the table, but I still don't have any Create Action in the All Custom Audit table.

<img width="854" alt="Screenshot 2024-01-06 141057" src="https://github.com/InformedPowerPlatform/MSFTPP.Plugins.CustomAudit/assets/114274846/c3e0ad1b-e24d-4934-a89f-6061e56c3905">
<img width="533" alt="Screenshot 2024-01-06 141121" src="https://github.com/InformedPowerPlatform/MSFTPP.Plugins.CustomAudit/assets/114274846/104e0087-5a69-430e-a8ac-b7b487748fce">

Additionally, as mentioned before, for Update it shows up in the Custom Audit table only for columns where there's already a data before, it doesn't detect if initially that column doesn't have any data (blank).

Appreciate your help, thank you.

**Comment by InformedPowerPlatform** [comment]
If you select that create step, what columns are you auditing? Can you give me a screenshot of that?

**Comment by Perestein** [comment]
Hi, thank you for your solution. I use it to log the changes in my tool that registers visitors of business events at our company.

Unfortunately I run into the same issue as user **clararichela**. The tool registers updated rows in my table 'Visitor' but not newly created rows. Some screenshots:

![image](https://github.com/user-attachments/assets/fba303d9-baa2-4a12-a7bf-b22db4dd6f59)

I've created new visitors in my tool, the table was updated, but the 'create' records are not displaved in the audit tool:

![image](https://github.com/user-attachments/assets/e4de706e-2b20-4f3b-82ad-1037597e0370)

What am I doing wrong?

Thanks in advance.

Kind regards,
Bas.

**Comment by InformedPowerPlatform** [comment]
Ok, I have checked and been able to reproduce the error. If you can confirm, please check the system jobs area in your advanced settings to see if you can also see the job failing. I will try to fix this over the weekend.

![image](https://github.com/user-attachments/assets/d4a52665-b594-4cbc-afda-ad6b8b47d057)

**Comment by Perestein** [comment]
Hi, I've checked and I get the same job failing:

![image](https://github.com/user-attachments/assets/34453de4-cd15-490d-a8e6-669ea1c5df63)

Thanks for trying to fix this.

Gr. Bas

**Comment by InformedPowerPlatform** [comment]
@clararichela, @Perestein 

Should be fixed now. There was an issue when the old or new values were null and needed to be converted to an empty string so they could be logged properly.

NOTE: I also had to rename the plugin assembly as it had a plural name and should not have. This may require that you rebuild your plugin registration steps from scratch for your tables. Sorry for any issues with that, but it could not be helped.

https://github.com/InformedPowerPlatform/MSFTPP.Plugins.CustomAudit/releases/tag/1.0.0.7

**Comment by Perestein** [comment]
After updating the solution and creating new plugin registration steps initially it looked like it worked but after refreshing the custom audit table I run into 2 issues:

It still does not register new rows in my table. The same job fails when creating a new record.

![image](https://github.com/user-attachments/assets/ca769988-87aa-46cd-929f-ec0588fc1a55)

Also the updated records are duplicated in the custom audit table:

![image](https://github.com/user-attachments/assets/ad5ee41c-9230-4d1d-bfb4-765d5df53a1d)

Does this duplication occur because of the plugin registration steps created in the previous version of the solution?

![image](https://github.com/user-attachments/assets/4f1fe9d9-2bd7-4aaf-a779-07999b896535)

Perhaps a stupid question: how do remove plugin registration steps in the solution?

**Comment by InformedPowerPlatform** [comment]
Yes, it is most likely because the steps are registered twice. Once with the old one and once with the new one. You'll have to use the Plugin Registration Tool to delete both of them just to be sure, then re-add them back with the new solution.


https://learn.microsoft.com/en-us/power-apps/developer/data-platform/register-plug-in

**Comment by Perestein** [comment]
I've removed the old steps and created new ones. All looks ok now.

![image](https://github.com/user-attachments/assets/6c7a42dc-2957-4e43-ae48-12d8d8c46f20)

Thank you very much.

Gr. Bas
